language: node_js
node_js:
  - “8.9.4”

branches:
  only: 
    - master

install:
  - npm install

before_script:
  - npm install -g ionic cordova
  - npm install -g @angular/cli

script:
  - ionic cordova build browser - prod
  - ng build --prod --aot
